#!/bin/sh

set -exu
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

working_dir=${1:-}

if [ -z "$working_dir" ]; then
  printf '\e[91m[ERROR]\e[0m usage: %s <path/to/source>\n' "$0"
  exit 1
fi

TMPDIR=${TMPDIR:-/tmp}
base=`basename $0`
payload=$(mktemp "$TMPDIR/${base}.XXXXXX")

cat > $payload <&0

tarfile=$(mktemp "$TMPDIR/${base}.XXXXXX").tar.gz

tar -cvzf $tarfile $working_dir

echo "{\"version\":{\"date\":\"`date -u`\", \"uuid\":\"`uuidgen`\", \"parcel\":\"`base64 $tarfile | tr '\n' '_-_'`\"}}" >&3
